In [30]:
import pandas as pd

In [31]:
df_train =pd.read_csv("Final_train.csv")

In [32]:
df_train

,OrgId,Category,IncidentGrade,EntityType,EvidenceRole,hour
0,0,InitialAccess,TruePositive,Ip,Related,6
1,88,Exfiltration,FalsePositive,User,Impacted,3
2,809,InitialAccess,FalsePositive,Url,Related,4
3,92,CommandAndControl,BenignPositive,Url,Related,16
4,148,Execution,TruePositive,User,Impacted,1
...,...,...,...,...,...,...
9516832,0,InitialAccess,TruePositive,CloudLogonRequest,Related,15
9516833,59,CommandAndControl,BenignPositive,Url,Related,9
9516834,44,Exfiltration,BenignPositive,MailMessage,Impacted,22
9516835,43,Impact,BenignPositive,Ip,Related,23
9516836,16,Exfiltration,BenignPositive,MailMessage,Impacted,23

In [33]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9516837 entries, 0 to 9516836
Data columns (total 6 columns):
 #   Column         Dtype
---  ------         -----
 0   OrgId          int64
 1   Category       object
 2   IncidentGrade  object
 3   EntityType     object
 4   EvidenceRole   object
 5   hour           int64
dtypes: int64(2), object(4)
memory usage: 435.6+ MB

In [34]:
df_train.isnull().sum()

OrgId                0
Category             0
IncidentGrade    51340
EntityType           0
EvidenceRole         0
hour                 0
dtype: int64

In [35]:
df_train.dropna(inplace=True)

In [68]:
9516837 - 51340

9465497

In [36]:
df_train.isnull().sum()

OrgId            0
Category         0
IncidentGrade    0
EntityType       0
EvidenceRole     0
hour             0
dtype: int64

In [37]:
df_train.select_dtypes(include=object).columns

Index(['Category', 'IncidentGrade', 'EntityType', 'EvidenceRole'], dtype='object')

In [45]:
object_columns= ['Category', 'IncidentGrade', 'EntityType', 'EvidenceRole']
print(object_columns)

['Category', 'IncidentGrade', 'EntityType', 'EvidenceRole']

In [39]:
for i in df_train.select_dtypes(include=object):
    print(i)
    print(df_train[i].unique())
    print(len(df_train[i].unique()))
    print("-----------------")

Category
['InitialAccess' 'Exfiltration' 'CommandAndControl' 'Execution'
 'SuspiciousActivity' 'Impact' 'Collection' 'CredentialAccess'
 'Persistence' 'Discovery' 'Malware' 'DefenseEvasion' 'Exploit'
 'PrivilegeEscalation' 'LateralMovement' 'Ransomware' 'UnwantedSoftware'
 'CredentialStealing' 'WebExploit' 'Weaponization']
20
-----------------
IncidentGrade
['TruePositive' 'FalsePositive' 'BenignPositive']
3
-----------------
EntityType
['Ip' 'User' 'Url' 'MailMessage' 'Process' 'Machine' 'CloudApplication'
 'AzureResource' 'File' 'Mailbox' 'CloudLogonRequest' 'MailCluster'
 'Malware' 'CloudLogonSession' 'OAuthApplication' 'RegistryValue'
 'SecurityGroup' 'RegistryKey' 'GenericEntity' 'ActiveDirectoryDomain'
 'BlobContainer' 'Blob' 'MailboxConfiguration' 'IoTDevice'
 'AmazonResource' 'Nic' 'Container' 'GoogleCloudResource'
 'KubernetesCluster' 'ContainerImage' 'KubernetesNamespace'
 'KubernetesPod' 'ContainerRegistry']
33
-----------------
EvidenceRole
['Related' 'Impacted']
2
-----------------

In [40]:
from sklearn.preprocessing import LabelEncoder

In [41]:
encoder={}
for cols in df_train.select_dtypes(include=object):
    le= LabelEncoder()
    df_train[cols] = le.fit_transform(df_train[cols])
    encoder[cols]=le

In [42]:
encoder

{'Category': LabelEncoder(),
 'IncidentGrade': LabelEncoder(),
 'EntityType': LabelEncoder(),
 'EvidenceRole': LabelEncoder()}

In [47]:
for i in object_columns:
    print(i)
    print(df_train[i].unique())
    print(len(df_train[i].unique()))
    print("-----------------")

Category
[10  7  1  6 16  9  0  2 13  5 12  4  8 14 11 15 17  3 19 18]
20
-----------------
IncidentGrade
[2 1 0]
3
-----------------
EntityType
[15 32 31 21 27 19  5  2 11 22  6 20 24  7 26 29 30 28 12  0  4  3 23 14
  1 25  8 13 16  9 17 18 10]
33
-----------------
EvidenceRole
[1 0]
2
-----------------

In [49]:
df_train.corr()

,OrgId,Category,IncidentGrade,EntityType,EvidenceRole,hour
OrgId,1.000000,0.077279,-0.013979,0.022078,0.010848,0.024453
Category,0.077279,1.000000,0.176012,-0.129349,0.042987,-0.038614
IncidentGrade,-0.013979,0.176012,1.000000,-0.142396,0.157652,-0.055853
EntityType,0.022078,-0.129349,-0.142396,1.000000,-0.389546,0.024556
EvidenceRole,0.010848,0.042987,0.157652,-0.389546,1.000000,-0.045313
hour,0.024453,-0.038614,-0.055853,0.024556,-0.045313,1.000000

In [56]:
df_test=pd.read_csv("Final_test.csv")

In [57]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4147992 entries, 0 to 4147991
Data columns (total 6 columns):
 #   Column         Dtype
---  ------         -----
 0   OrgId          int64
 1   Category       object
 2   IncidentGrade  object
 3   EntityType     object
 4   EvidenceRole   object
 5   hour           int64
dtypes: int64(2), object(4)
memory usage: 189.9+ MB

In [58]:
df_test.isnull().sum()

OrgId            0
Category         0
IncidentGrade    0
EntityType       0
EvidenceRole     0
hour             0
dtype: int64

In [59]:
encoder

{'Category': LabelEncoder(),
 'IncidentGrade': LabelEncoder(),
 'EntityType': LabelEncoder(),
 'EvidenceRole': LabelEncoder()}

In [60]:
for i in object_columns:
    print(i)
    print(df_test[i].unique())
    print(len(df_test[i].unique()))
    print("-----------------")

Category
['LateralMovement' 'CommandAndControl' 'InitialAccess' 'Discovery'
 'SuspiciousActivity' 'Impact' 'CredentialAccess' 'Exfiltration'
 'UnwantedSoftware' 'DefenseEvasion' 'Malware' 'Execution' 'Persistence'
 'CredentialStealing' 'Collection' 'Ransomware' 'Exploit'
 'PrivilegeEscalation' 'WebExploit']
19
-----------------
IncidentGrade
['BenignPositive' 'FalsePositive' 'TruePositive']
3
-----------------
EntityType
['User' 'Machine' 'Process' 'CloudLogonSession' 'Ip' 'File' 'MailMessage'
 'CloudLogonRequest' 'Url' 'CloudApplication' 'MailCluster' 'Mailbox'
 'RegistryValue' 'AzureResource' 'GenericEntity' 'Malware' 'RegistryKey'
 'OAuthApplication' 'Blob' 'MailboxConfiguration' 'SecurityGroup'
 'BlobContainer' 'ActiveDirectoryDomain' 'Nic' 'IoTDevice'
 'KubernetesNamespace' 'KubernetesCluster' 'GoogleCloudResource'
 'AmazonResource']
29
-----------------
EvidenceRole
['Impacted' 'Related']
2
-----------------

In [ ]:
['Related' 'Impacted'] - [1 0]

In [61]:
df_test["Category"] = encoder.get('Category').transform(df_test["Category"])
df_test["IncidentGrade"] = encoder.get('IncidentGrade').transform(df_test["IncidentGrade"])
df_test["EntityType"] = encoder.get('EntityType').transform(df_test["EntityType"])
df_test["EvidenceRole"] = encoder.get('EvidenceRole').transform(df_test["EvidenceRole"])

In [62]:
for i in object_columns:
    print(i)
    print(df_test[i].unique())
    print(len(df_test[i].unique()))
    print("-----------------")

Category
[11  1 10  5 16  9  2  7 17  4 12  6 13  3  0 15  8 14 19]
19
-----------------
IncidentGrade
[0 1 2]
3
-----------------
EntityType
[32 19 27  7 15 11 21  6 31  5 20 22 29  2 12 24 28 26  3 23 30  4  0 25
 14 17 16 13  1]
29
-----------------
EvidenceRole
[0 1]
2
-----------------

In [64]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4147992 entries, 0 to 4147991
Data columns (total 6 columns):
 #   Column         Dtype
---  ------         -----
 0   OrgId          int64
 1   Category       int64
 2   IncidentGrade  int64
 3   EntityType     int64
 4   EvidenceRole   int64
 5   hour           int64
dtypes: int64(6)
memory usage: 189.9 MB

In [54]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report

In [66]:
x_train = df_train.drop("IncidentGrade",axis=1)
y_train = df_train["IncidentGrade"]
x_test = df_test.drop("IncidentGrade",axis=1)
y_test = df_test["IncidentGrade"]

In [67]:
x_train

         OrgId  Category  EntityType  EvidenceRole  hour
0            0        10          15             1     6
1           88         7          32             0     3
2          809        10          31             1     4
3           92         1          31             1    16
4          148         6          32             0     1
...        ...       ...         ...           ...   ...
9516832      0        10           6             1    15
9516833     59         1          31             1     9
9516834     44         7          21             0    22
9516835     43         9          15             1    23
9516836     16         7          21             0    23

[9465497 rows x 5 columns]

In [69]:
x_test

         OrgId  Category  EntityType  EvidenceRole  hour
0          657        11          32             0    22
1            3         1          19             0    12
2          145        11          27             1     3
3          222        10           7             1    12
4          363         5          32             0    17
...        ...       ...         ...           ...   ...
4147987    262        10          32             0     3
4147988   1323        10          32             0    19
4147989     47         1          15             1     0
4147990     70        10          22             0    16
4147991    227        10          22             0    18

[4147992 rows x 5 columns]

In [71]:
model1=RandomForestClassifier().fit(x_train,y_train)
y_pred = model1.predict(x_test)
accuracy = accuracy_score(y_test,y_pred)
precision = precision_score(y_test,y_pred, average="weighted")
recall = recall_score(y_test,y_pred, average="weighted")
f1_score = f1_score(y_test,y_pred, average="weighted")

print(f"Accuracy : {accuracy:.2f}")
print(f"Precision : {precision:.2f}")
print(f"Recall : {recall:.2f}")
print(f"F1_Score : {f1_score:.2f}")

# Detailed classification report
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy : 0.91
Precision : 0.91
Recall : 0.91
F1_Score : 0.91

Classification Report:

              precision    recall  f1-score   support

           0       0.92      0.92      0.92   1752940
           1       0.85      0.85      0.85    902698
           2       0.93      0.93      0.93   1492354

    accuracy                           0.91   4147992
   macro avg       0.90      0.90      0.90   4147992
weighted avg       0.91      0.91      0.91   4147992